name: mirize
description: A new Flutter project.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  firebase_core: ^0.5.0
  storage_path: ^0.2.0
  fluttericon: ^1.0.7
  firebase_analytics: ^6.0.0
  firebase_auth: ^0.18.0+1
  firebase_storage: ^4.0.0
  firebase_database: ^4.0.0
  simple_animations: ^2.2.2
  cupertino_icons: ^1.0.0
  camera: ^0.5.8+11
  path_provider: ^1.6.22
  path: ^1.7.0
  flutter_lantern: ^0.0.1
  gallery_saver: ^2.0.1
  cached_network_image: ^2.2.0+1
  provider: ^4.3.2+2
  cloud_firestore: ^0.14.4
  uuid: ^2.0.0
  image_picker: ^0.6.2
  package_info: ^0.4.1
  shared_preferences: ^0.5.1+2
  firebase_messaging: ^6.0.13
  intl: ^0.16.1
  geocoder: ^0.2.1
  geolocator: ^6.1.10
  firebase_remote_config: ^0.3.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_launcher_icons: "^0.8.0"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/rounted/rounted_icon_100.png"


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/logo/
    - assets/images/icon_logo/
    - assets/images/rounted/
    - assets/fonts/
    - assets/lang/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Bold.ttf
    - family: TwitterIcon
      fonts:
        - asset: assets/fonts/icons.ttf
